#!/bin/bash

# create merged bam file
module load samtools
samtools merge -@ 8 GSF4155-HAE-input.merged.bam GSF4155-HAE-input-rep1_S13_R1_001_Aligned.sortedByCoord.out.bam GSF4155-HAE-input-rep3_S14_R1_001_Aligned.sortedByCoord.out.bam 

#create a .json file (on text editor Pluma) with the following contents (I saved it as GSF3037-N2rep1.json):
{
	"samples_path": "/N/slate/emierdma/GSF4155/flare",
	"samples": [ 
	"GSF4155-HAE-input.merged.bam"
	],
	"reverse_stranded": true,
	"reference_fasta": "/N/slate/emierdma/GSF4155/genome/assembly.fasta",
	"known_snps": "/N/slate/emierdma/GSF4155/flare/c.elegans.WS275.snps.nostrand.sorted.bed",
	"edit_type": "AG", 
	"output_dir": "/N/slate/emierdma/4155/results/flare_results"
}

#in flare directory
#load "rnaseq" conda environment
module load conda
conda activate rnaseq

#load singularity every single time you run 
module load apptainer

#use the following command to run SAILOR. under "--singularity-args --'bind' you will have to give access to every single directory that has relevant files
snakemake --snakefile /N/slate/emierdma/GSF4155/flare/workflow_sailor/Snakefile --configfile /N/slate/emierdma/GSF4155/flare/HAEmerged.json --use-singularity --singularity-args '--bind /N/slate/emierdma/GSF4155 --bind /N/slate/emierdma/GSF4155/flare --bind /N/slate/emierdma/GSF4155/genome --bind /N/slate/emierdma/GSF4155/flare/workflow_sailor/scripts --bind /N/slate/emierdma/GSF4155/flare/workflow_sailor --bind /N/slate/emierdma/GSF4155/results/flare_results' -j1

#editing site annotation
#in "annotation" conda environment (must have python==3.8.6, pybedtools, pandas)
#must have annotation .bed file, geneset .gtf file, annotator.sailor.py, .bed files from flare_results directory (directory 7)
python3 annotator.sailor.py --gtf c_elegans.PRJNA13758.WS275.canonical_geneset.gtf --fwd GSF4155-HAE-input.merged.bam.fwd.readfiltered.formatted.varfiltered.snpfiltered.ranked.bed --rev GSF4155-HAE-input.merged.bam.rev.readfiltered.formatted.varfiltered.snpfiltered.ranked.bed --wb c.elegans.WS275.annotation.final.bed --o /N/slate/emierdma/GSF4155/results/flare_results/HAE-input.annotated.sites.csv
