#!/bin/bash

#Make directory for variant calling within slate folder for project (/N/slate/emierdma/GSF3231)

mkdir Variantcall

#copy genome file, snp file, and aligned bam into Variantcall directory

scp assembly.fasta 
scp c.elegans_WS275.snps.sorted.bed
scp *.merged.bam

#remove duplicate reads from bam file (takes ~5 minutes per file)

samtools rmdup GSF4155-HAE-input.merged.bam HAEinputfile.nodup.bam

#Call the variant and clean up the output file with one line (takes hours- run overnight) 

bcftools mpileup -Ou -f assembly.fasta -a DP4 HAEinputfile.nodup.bam \
  | bcftools call -mv -Ov \
  | awk '$5 != "<*>"' \
  | tail -n +30 > HAE.rmdup.mpileup.vcf

#deactivate rnaseq environment

conda deactivate

#copy variant.py file into Variantcall directory (in terminal, off carbonate)

scp ~/Desktop/variant.py emierdma@carbonate.uits.iu.edu:/N/slate/emierdma/GSF3231/Variantcall

#convert vcf files to csv to open in excel

python variant.py --v HAE.rmdup.mpileup.vcf --snp c.elegans.WS275.snps.sorted.bed --o HAEvariant.csv 

#open csv in R studio to see how many rows it has

library("tidyverse")

library("GenomicRanges")

variants <- read.csv("/N/slate/emierdma/GSF3231/Variantcall/N2variant.csv")

View(variants)

#if the table is >1,000,000 rows, the csv will not open in excel and needs to be split into parts

var1 <- dplyr::slice(variants, 1:1000000)

write.table(var1, "HAEvariants_1.tsv", sep = "\t", col.names = TRUE, row.names = FALSE, quote = FALSE)

#repeat until whole table is split up. For final section you can use:

var7 <- dplyr::slice(variants, 6000001:nrow(variants))

#tsv files will now be in your Variantcall directory, can be copied to desktop and opened in excel for analysis.
